### ISSUE TITLE
Prepare codelab for Maps to use version 1.0

### ISSUE THREAD

**Issue by Nevraeka** [robdodson/itshackademic#8]
As discussed in our GDE meeting, I am creating this issue so that we have not conflicts with others working on updates. @deebloo & I will be working on this lab next week

**Comment by robdodson** [comment]
Closing as I think these have been updated now

**Comment by Nevraeka** [comment]
:+1: sorry we didnt get to it in time @robdodson :(

**Comment by robdodson** [comment]
No worries!
